all:
  vars:
    ansible_user: ubuntu
    ansible_become: true
  children:
    edge:
      hosts:
        edge-01: { ansible_host: 203.0.113.10 }
    controlplane:
      hosts:
        k8s-cp-01: { ansible_host: 203.0.113.11 }
    workers:
      hosts:
        k8s-w-01: { ansible_host: 203.0.113.12 }
        k8s-w-02: { ansible_host: 203.0.113.13 }
    observability:
      hosts:
        obs-01: { ansible_host: 203.0.113.14 }
    operations:
      hosts:
        ops-01: { ansible_host: 203.0.113.15 }
